package finalapp;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author BHAVANI
 */
public class OptFrame extends javax.swing.JFrame {
   
     TCPServer tp=new TCPServer(new TCPServer.OnMessageReceived() {
         
         @Override
         public void messageReceived(String message) {
             try {
                 UIManager.put("OptionPane.minimumSize",new Dimension(200,200));
                 UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                 JOptionPane.showMessageDialog(null,message,"Reply",JOptionPane.PLAIN_MESSAGE);
             } catch (Exception ex) {
                 Logger.getLogger(OptFrame.class.getName()).log(Level.SEVERE, null, ex);
             } 
            
            
         }
     });
    /**
     * Creates new form OptionsFrame
     */
    public OptFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,screenSize.width, screenSize.height-50);
        jPanel1.setSize(screenSize.width, screenSize.height-80);
        GridLayout gd=new GridLayout(2, 2);
        jPanel1.setLayout(gd);
//       
        jPanel1.add(foodBtn);
        
        jPanel1.add(restBtn);
         jPanel1.add(waterBtn);
        
        jPanel1.add(sleepBtn);
        
        add(jPanel1);
        setVisible(true);
       tp.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foodBtn = new javax.swing.JButton();
        restBtn = new javax.swing.JButton();
 waterBtn = new javax.swing.JButton();
        sleepBtn = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        foodBtn.setText("Food");         
        restBtn.setText("RestRoom");
        waterBtn.setText("Water");         
        sleepBtn.setText("Sleep");
        
        foodBtn.setFont(new Font("Arial", Font.PLAIN, 40));
         restBtn.setFont(new Font("Arial", Font.PLAIN, 40));
         waterBtn.setFont(new Font("Arial", Font.PLAIN, 40));
         sleepBtn.setFont(new Font("Arial", Font.PLAIN, 40));
        pack();
        
       foodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                sendMsg(evt,"Want food");
            }

           
        });
        restBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                sendMsg(evt,"Want to use restroom");
            }

           
        });
         waterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                sendMsg(evt,"Want: Water");
            }

           
        });
        sleepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                sendMsg(evt,"Want to sleep");
            }

           
        });

    }        
     private void sendMsg(ActionEvent evt,String message) {                  
           tp.sendMessage(message);
            }
 
      
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton exit;
    javax.swing.JButton foodBtn;
    private javax.swing.JPanel jPanel1;
     javax.swing.JButton restBtn;
       javax.swing.JButton sleepBtn;
     javax.swing.JButton waterBtn;
    // End of variables declaration                   
}
