package finalapp;


import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

/**
 *
 * @author BHAVANI
 */
public class OptFrame extends javax.swing.JFrame {
     TCPServer tp=new TCPServer();
    /**
     * Creates new form OptionsFrame
     */
    public OptFrame() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,screenSize.width, screenSize.height-50);
        jPanel1.setSize(screenSize.width, screenSize.height-80);
        GridLayout gd=new GridLayout(2, 2);
        jPanel1.setLayout(gd);
//       
        jPanel1.add(foodBtn);
        jPanel1.add(waterBtn);
        jPanel1.add(restBtn);
        jPanel1.add(sleepBtn);
        
        add(jPanel1);
        setVisible(true);
       tp.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foodBtn = new javax.swing.JButton();
        waterBtn = new javax.swing.JButton();
        restBtn = new javax.swing.JButton();
        sleepBtn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
         
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        foodBtn.setText("Food");
         
        waterBtn.setText("Water");

        restBtn.setText("RestRoom");

        sleepBtn.setText("Sleep");

        exit.setText("Exit");

        pack();
        
       foodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                foodBtnActionn(evt);
            }

           
        });
       waterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                waterBtnAction(evt);
            }

        });
       sleepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                sleepBtnAction(evt);
            }

           
        });
       restBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
           
                restBtnAction(evt);
            }
        });
    }        
     private void restBtnAction(ActionEvent evt) {
       
                    
           tp.sendMessage("Want to go to restroom");
            }
      private void foodBtnActionn(ActionEvent evt) {
          
                tp.sendMessage("Want food");
            }
      
    private void sleepBtnAction(ActionEvent evt) {
        
       tp.sendMessage("Want to sleep");
    }

private void waterBtnAction(ActionEvent evt) {
;
 tp.sendMessage("Want water");
}

    // Variables declaration - do not modify                     
    private javax.swing.JButton exit;
    javax.swing.JButton foodBtn;
    private javax.swing.JPanel jPanel1;
     javax.swing.JButton restBtn;
     javax.swing.JButton sleepBtn;
     javax.swing.JButton waterBtn;
    // End of variables declaration                   
}
